### ISSUE TITLE
grant approval workflow

### ISSUE THREAD

**Issue by edbennett** [edbennett/cogs3#10]
on adding a grant attribution to a project, if the grant has not already been attributed by a user, the PI should be emailed a request to confirm. this is by clicking a mailto: link that generates a pre-filled email with the text the EU requires. this email then goes to a specified person for processing offline.

**Comment by edbennett** [comment]
- The workflow should only be available if the Institution requires it
- A FundingSource can be approved or unapproved
- A FundingSource has a list of associated users, each with a flag of whether they have been approved to attribute the FundingSource with their projects

- When a CustomUser tries to create a FundingSource, they are initially prompted only for the institutional funding ID (e.g. AMS ID).
- When a CustomUser tries to create a FundingSource with a combination of institutional funding ID and Institution that is in the database, the CustomUser is presented with a warning/confirmation screen that an email is about to be sent to the PI requesting their approval for the CustomUser to access the grant.
- If the CustomUser confirms, then they are added to the list of users for that FundingSource in an unapproved state, and the server sends an email to the PI requesting they approve access (exact text tbc)
.
- When a CustomUser creates a FundingSource with a combination of institutional funding database ID and Institution not already in the database, the CustomUser is presented a second step requesting the grant title and amount attributable to SCW, along with a warning/confirmation message indicating that an email is about to be sent to the PI requesting that they confirm attribution of the grant to SCW.
- When the CustomUser provides these details and confirms that sending an email to the PI is OK, the server sends an email to the PI, and the FundingSource is created with the requesting CustomUser in the list of pending users
- The email (exact text tbc) explains that the CustomUser has indicated that a grant of which they are PI is attributable to SCW, and requests that they confirm this by clicking the below link and sending the resulting email. There is then a mailto: link that creates a second email.
- The second email has some predefined text (tbc) giving the grant title, AMS ID, £ amount attributable to SCW, and possibly the name of the funding body.
- The second email is addressed to the local Supercomputing Wales PI at the Institution (by name and email address), and CCed to a member of administrative staff at the Institution with access to the grants database (by email address only)

- CustomUsers can have permissions to approve FundingSources
- CustomUsers with permission to approve FundingSources can see lists of approved and unapproved FundingSources
- When a CustomUser with permission to approve FundingSources has confirmed with the grants database that the PI is in fact PI of the grant in question, and that the amount attributed is within the total amount of the grant, they can approve the FundingSource
- If the CustomUser with permission to approve FundingSources finds that the contents of the email received differ from the details on the FundingSource object, they can edit the FundingSource object to match
- When a FundingSource is marked as approved, the CustomUser who raised the request is marked as approved on the list of users associated with the FundingSource. (This requires storing their identity in whatever table is storing the list of requests for approval.)
- When a FundingSource is marked as approved, the PI is added to the list of users for that FundingSource and is marked as approved there.

- A CustomUser who is a PI on one or more grants which have pending users is able to access a view where they can approve these users. This is accessible from a link on the Dashboard, which is otherwise hidden.
-  If the CustomUser's status is still Awaiting Approval, they are regardless still able to access this view.

@rantahar @M4rkD Can you see any holes in this process?

**Comment by rantahar** [comment]
This is a small implementation detail, but we could actually do without the separate lists for pending users and approved users if we use an explicit joint table ( 'through' argument for the manytomany field ) and add a 'approved' field there.

Although it is easier to list approved and unapproved users if there are two separate lists.

**Comment by edbennett** [comment]
Mark raised that option as well, also pointing out that that way, the database transaction would be atomic (change a single variable vs remove a foreign key from one list and then add it to a second) and thus less prone to failure.

**Comment by edbennett** [comment]
Just had feedback from Biagio/Ellie that an email is not sufficient to satisfy WEFO, so we will need to instead generate a form letter for the PI to fill out, print on headed notepaper, and send back to us.
