### ISSUE TITLE
users awaiting authorisation from Cardiff/Bangor can be invited to approved projects

### ISSUE THREAD

**Issue by mmesiti** [edbennett/cogs3#103]
At the moment if a user (from an istitution requiring the "user approval" workflow) is not yet approved she/he can be invited to approved projects. This should not be possible.

**Comment by edbennett** [comment]
@tystakartografen the Invite button to allow tech leads to add users to a project is a new feature. Currently it is enabled for all sites as a quality of life improvement and as it isn't related to the attribution workflow. This issue isn't a case for Swansea and Aber, as we have opted to automatically approve new users. How would you like to handle this case for Cardiff and Bangor, where you are still manually approving users?

* Disable the Invite button for Cardiff and Bangor?
* Enable the Invite button for Cardiff and Bangor, but raise a validation error when attempting to add a user who isn't yet approved?
* Enable the Invite button for Cardiff and Bangor, allow unapproved users to be added to approved projects, but prevent cluster access until they are approved by an administator?
* Enable the Invite button for Cardiff and Bangor, allow unapproved users to be added to projects, and automatically approve users once they are added to an approved project?

Thanks!

**Comment by edbennett** [comment]
Answer from Aaron:

> I think the invite users feature should be enabled for Cardiff and Bangor but raise a validation error when a tech lead attempts to add a user who isn't yet approved. This is probably the cleanest logic and informs the tech lead as to why a user can't access their approved project.

**Comment by mmesiti** [comment]
(supposedly) fixed on 80acbcca2d0c678a05a431a65009900bb37b4aa0 (https://github.com/mmesiti/cogs3/commit/80acbcca2d0c678a05a431a65009900bb37b4aa0)
