### ISSUE TITLE
Testing: unit test for user_created_notification required

### ISSUE THREAD

**Issue by markgdawson** [edbennett/cogs3#118]
A simple unit test is required that calls the user_created_notification with a valid user.

As a minimum this should check that there are no errrors.

Potentially could test institutional and non-institutional emails. Ideally should check that the email_user is at least called properly (or alternatively the sent email is formatted as expected).

Note that this calls Institution.parse_support_email_from_user_email which has 100% test coverage, so we can assume (at least notionally) that the behaviour of this function is outside the test scope.

**Comment by M4rkD** [comment]
Ouch, I just did this... but presumably so did you... Are you done?

**Comment by edbennett** [comment]
This function shouldn't be called for non-institutional users, so I've just tested this for institutional users.
