### ISSUE TITLE
ToggleFundingSourceMembershipApproved

### ISSUE THREAD

**Issue by markgdawson** [edbennett/cogs3#127]
This view is not tested at all in the test suite.

**Comment by markgdawson** [comment]
Tests created in m4rkd@64d4e1fbeaa3603c598b241ae401f3ea02b1c5df, but the feature seems to be broken. Should the feature be removed?

**Comment by edbennett** [comment]
The feature works—the approving and retracting approval from users of a given FundingSource is done via this view. It's not designed to be viewed as its own page, however (so perhaps shouldn't  be a View?), so tests trying to render it directly fail.

**Comment by edbennett** [comment]
I've just pushed https://github.com/M4rkD/cogs3/commit/98cfbbb450d4b53d9e10712eff2f979c47a359f4 which allows the view to render and allows the test to pass by removing one of the asserts. In principle we should test the content as well, but currently the content returned isn't what I expect and I'm not sure why.

**Comment by markgdawson** [comment]
Reopening issue for discussion
