### ISSUE TITLE
Funding source details created cannot be accessed

### ISSUE THREAD

**Issue by mmesiti** [edbennett/cogs3#134]
looking at `funding/list/`, clicking on any funding source redirects to `funding/list` again. The issue lies in `FundingsourceDetailView.user_passes_test`, that always returns `False`.

**Comment by mmesiti** [comment]
The problem I see is that fixing this without complete understanding of what's going on may cause security issues?

**Comment by markgdawson** [comment]
You almost certainly know this, but this is actually a problem in the funding source detail view, redirecting to list when user is unapproved.

**Comment by mmesiti** [comment]
exactly. 
We worked out that this happens only when the funding source is not approved. When the funding source is approved, `FundingSource.save` actually creates the pre-approved `FundingSourceMembership`s for the creator (and the pi if necessary).

**Comment by mmesiti** [comment]
after the funding source has been approved, memberships for the creator (and pi if necessary) are added automatically in the approved status, so that the creator (and the pi if necessary) can access the funding source.
Maybe close?

**Comment by edbennett** [comment]
I think this is closable now…
