### ISSUE TITLE
`Project.save` should not always call `_assign_project_owner_project_membership()`

### ISSUE THREAD

**Issue by edbennett** [edbennett/cogs3#14]
On saving a change to a project, the update tries to assign the project owner project membership, which fails because they're already there, raising a stack of data integrity errors, and spamming them into the log.

**Comment by rantahar** [comment]
The function was already using objects.get_or_create(), but incorrectly. It would not match the existing membership and therefore try to create a new one. Using defaults fixes this behaviour.
