### ISSUE TITLE
notify_supervisor not tested

### ISSUE THREAD

**Issue by markgdawson** [edbennett/cogs3#157]
... since we never create project where supervisor is not the tech lead

**Comment by edbennett** [comment]
weird—the selenium tests appear to do this. created by `user@example.ac.uk`, who we check is the tech lead, but the `id_supervisor_email` is set to `joe.bloggs@example2.ac.uk`.

**Comment by markgdawson** [comment]
You're right Ed, this appears to be tested now. Closing.
