### ISSUE TITLE
Remove the manual user approval step for Swansea/Aber users

### ISSUE THREAD

**Issue by edbennett** [edbennett/cogs3#22]
New users are able to request projects and request to join projects. Users will move to the approved state and gain LDAP accounts once they are members of a project that has been approved.

**Comment by rantahar** [comment]
At the moment there is a user group on the system for each project and all approved project members are also added to the group. I would suggest creating the user on the system when the user is added as a member.

This would mean that there are users with an HPC account who have never had an active project. Would that be a problem?

**Comment by edbennett** [comment]
> there is a user group on the system for each project

For each project, or for each approved/active project?

> This would mean that there are users with an HPC account who have never had an active project. 

Legacy users, or would new users have a way of getting an HPC account without membership of an active project? The aim of this feature is to prevent new users getting HPC accounts before they have a project, so that either we can review their project request to see what they're going to do with the system, or a PI can decide that they need HPC access. 

(Currently the workflow is that they sign in to cogs, supply their name and a "reason for access to Supercomputing Wales", and Ian/Gareth has to decide whether to activate their account based on almost no information. If they are approved they immediately get an HPC account with no project. This is what we're trying to avoid.)

Does that make sense?

**Comment by rantahar** [comment]
Ok, I'm writing a workflow in which users get added only once they are in an approved project.

This way the projects get reviewed before authorisation and no user are added before the project is approved. It is possible for a tech lead of an approved project to add a user, which will create a new account for that user.
