### ISSUE TITLE
Funding source tests removed

### ISSUE THREAD

**Issue by markgdawson** [edbennett/cogs3#30]
Need tests that funding source is being added to funding source list when created on the project page. Currently this is not tested. Should follow workflow from:

project.tests.test_integration.ProjectIntegrationTests.test_create_project

**Comment by markgdawson** [comment]
I've removed the tests for this from the method mentioned above. There were two, once for funding source and one for publication. Removed because currently this isn't supported (i.e. if you create a funding source it doesn't appear in your list until after the PI has responded to the email).

We both agree that this is confusing behaviour and should be changed.

(I think this is the same behaviour which caused some confusion in the SCW day presentation?)

**Comment by edbennett** [comment]
Huh, that lack of immediacy for having the checked box appear and getting the grant associated with the project is annoying. 

I guess we could surface the status of the grant to the user and let them know that there is an unapproved grant that they can associate with a project, but that it won't count towards priorities until it is approved. Reserve that for phase-3 though.

**Comment by markgdawson** [comment]
I've mentioned this to Jarno, I think as long as the title reads something like:

My Funding Title (Awaiting Approval)

that would be the best approach. Taking actions that don't have visible effects is confusing.

**Comment by edbennett** [comment]
Does this mean that the removed tests can be re-added?

**Comment by edbennett** [comment]
> I've removed the tests for this from the method mentioned above. 

@M4rkD I don't see this change in the commit log for the date you posted this message… Do you know what you meant by this?

**Comment by edbennett** [comment]
After conversation with Mark, the tests removed seem to be covered elsewhere; closing for now and we'll let the coverage report guide the need for testing any uncovered code paths.
