### ISSUE TITLE
Fixing tests for Swansea leaves Cardiff behaviour untested

### ISSUE THREAD

**Issue by markgdawson** [edbennett/cogs3#31]
The following tests have been adapted to work under default behaviour:

ProjectIntegrationTests:
   test_create_project
   test_create_project_missing_fields

The previous behaviour should also be tested by another set of tests for the Cardiff system.

**Comment by edbennett** [comment]
Again related to @mmesiti's current work.

**Comment by bjthorpe** [comment]
I'm a little confused here we have 7 tests in ProjectIntegrationTests.

The first 3 of which cover missing fields cases for both behaviours:

- test_create_project_missing_fields

- test_create_allocation_missing_fields 

- test_create_project_and_allocation_missing_fields

The next two then the project creation for both behaviours:

- test_create_project_with_authorised_user

- test_create_project_and_allocation

and finally, 2 test unauthorised and external project creation (both of which should not be possible). So as far as I can see both behaviours are covered unless were talking about something different.

**Comment by markgdawson** [comment]
Good job looking it up @bjthorpe. Looks like those tests where written after the issues was raised.

I think we can probably close this since it looks to have been fixed since the issue was raised.

**Comment by edbennett** [comment]
Thanks Mark, closing now
