### ISSUE TITLE
Test workflows when user approval is not needed

### ISSUE THREAD

**Issue by rantahar** [edbennett/cogs3#34]
### In phase-2a
Workflows with an institution that does not require user approval have not been written. Normal workflows should work when a user
* is a member if an institution with needs_user_approval = False
* and user.profile.status = awaiting approval.

When this user is
* added to an approved project or
*  a member of a project that gets approved
the user should become approved (and an account should be created on LDAP)

**Comment by edbennett** [comment]
This relates to what @mmesiti is working on now.

**Comment by mmesiti** [comment]
I actually need to know: what are the features/workflows that should not be available 
if user.profile.status == AWAITING_APPROVAL and user.profile.institution.needs_user_approval ? 

It's not clear to me. Looking at the dashboard in this situation, for example:
1. they are able to create projects
2. they are not able to join a project (there is no 'join' section)

**Comment by edbennett** [comment]
That sounds correct—that's the behaviour on MySCW at the moment. I think they also shouldn't be able to be invited to a project, although I'm not 100% sure that's implemented. Also, they don't see their SCW username in the dashboard.

(This is unlikely to be malfunctioning since the `needs_user_approval=False` behaviour is to jump users straight into `user.profile.status == APPROVED`, so the behaviour for `AWAITING_APPROVAL` hasn't been touched. The invitation functionality is new, hence my being less certain over how it handles that state.)

**Comment by mmesiti** [comment]
A comment: if they are not able to join a project (neither via 'join project', nor via invitation), then the only way for a user to get to the approved state are:
* by approval by an admin
* by approval of a project of him/her by an admin.
which removes the possibilty of getting approved by getting 'added to an approved project' (see jarno's comment https://github.com/edbennett/cogs3/issues/34#issue-362205818)

**Comment by mmesiti** [comment]
Some comments on the current situation:
* at the moment an unapproved user (from an institution that requires user approval) can create projects  and after creating it is redirected to the  project list, but on the dashboard there is no link to see the project list (even if it can access the /projects/applications/ url) [just opened issue #101 for this]. 
* it is possible for a user (from an institution that requires user approval) awaiting approval can be invited to an approved project (if a project is not approved the invitation does not work)

**Comment by edbennett** [comment]
> A comment: if they are not able to join a project (neither via 'join project', nor via invitation), then the only way for a user to get to the approved state are:
>
> by approval by an admin
> by approval of a project of him/her by an admin.

Approval by admin is the current documented way that a user can enter the approved state at sites that require user approval.

> which removes the possibilty of getting approved by getting 'added to an approved project' (see jarno's comment #34 (comment))
> it is possible for a user (from an institution that requires user approval) awaiting approval can be invited to an approved project

Ah, I missed that. That is a great feature, but we've been asked to ensure that there are no changes to the functionality for Cardiff/Bangor in this update, so I suspect we'll have to remove this for the moment.

**Comment by mmesiti** [comment]
I have now verified that cardiff users awaiting approval can actually be invited to projects. 
Should I raise this as issue?

**Comment by mmesiti** [comment]
done (see #103)
