### ISSUE TITLE
Short email addresses not accepted in project creation form

### ISSUE THREAD

**Issue by markgdawson** [edbennett/cogs3#61]
Only long institutional email addresses are accepted in project creation form (and everywhere else).

Supporting the short and long institutional domains (by translation to shorter domain names) could make this less confusing for users in general. Especially given that users appear to be stored by short domain name.

**Comment by markgdawson** [comment]
After some digging, I'm not sure if the statement about storing users by short domain is correct. My current suspicion is that dev and live institution table have different domain names.

**Comment by edbennett** [comment]
Switching to the long institution domain name in the fixture is a change on the phase 2 branch. I’m not entirely sure that the fixtures are actually used anywhere on the live site; they certainly weren’t used to spin up the phase 2 test server  

Personally I think people are more likely to try the long that the short institution domain, but most of the time the email will be silently supplied by the Shibboleth identity provider anyway

**Comment by markgdawson** [comment]
I'm 100% convinced that you're right about long being better than short. Not convinced that we've resolved this by changing fixtures. I'm assuming that Aaron won't use them.


I'd be inclined to revert the fixtures. The only thing I think we'll accomplish by changing fixtures (unfortunately) is making dev and live inconsistent.

Having said that, I'm definitely on board with the idea of supporting long domain names. Maybe we should re-open the issue and have a look at this after the current release?

**Comment by markgdawson** [comment]
@edbennett can we agree to roll this back for now? Or do we need a chat about it?

**Comment by markgdawson** [comment]
Closing since resolved in M4rkD/master

Opening issue #89 to track changes in error messages thrown when long domain used.
