### ISSUE TITLE
Saving twice in create-funding-source is confusing

### ISSUE THREAD

**Issue by markgdawson** [edbennett/cogs3#62]
To my mind, having to click save twice is confusing in
http://localhost:8000/en/funding/create-funding-source/

A more conventional approach would be for the form to redirect to the info page for the resource, and for the status message to be displayed on the info page.

Alternatively a popup would also work, but seems to me this adds complexity without much benefit.

**Comment by edbennett** [comment]
> A more conventional approach would be for the form to redirect to the info page for the resource, and for the status message to be displayed on the info page.

Until the user hits Save the first time, Cogs doesn't know whether the email will be sent to the user or to someone else. The intent of the second Save is to get the user to confirm that they are OK with an email being sent to the grant PI requesting attribution. In principle this could also be done with Javascript, but that obviously wouldn't work with JS disabled.

**Comment by markgdawson** [comment]
You're right, my approach wouldn't currently work. What about a message about the PI field with something like:
"Note that the PI will be notified by email and asked to attribute the funds to SCW."

Then we can only submit once and redirect to an info page that gives the rest of the info?

**Comment by edbennett** [comment]
I think my secondary thinking was that having to confirm twice guarded against hitting "enter" too early and accidentally submitting a half-complete form, and giving a chance to check the data before doing something irrevocable. However, I think that a better way to do that (and a version I've seen elsewhere) would be to show a read-only version of the form, with the option to go "back" and correct it or to "submit". I think it's best to go with your solution for now and then open a new issue for the confirmation screen to be on the back burner.

**Comment by markgdawson** [comment]
Resolved by M4rkD/cogs3#11
