### ISSUE TITLE
Publications/Funding IDs for Aber

### ISSUE THREAD

**Issue by markgdawson** [edbennett/cogs3#67]
We need to confirm what validation is required on both the funding and publications for Aber and implement this.

Also there may be need for a (helpful) message in the form to instruct users what is required/expected.

**Comment by edbennett** [comment]
relevant Slack conversation:

> Ed Bennett 12:04 PM
> that answers another question we had; is “finance code” a good word to describe what we request from users as an identifier for a particular grant?
> Colin Sauze 12:04 PM
> I think the official term is work order code

**Comment by edbennett** [comment]
We don't currently do any validation on AMS IDs. I think encoding validation rules into the Institution model is beyond what we can achieve in this sprint, so could be opened as another issue if it's something we think is worthwhile.

**Comment by markgdawson** [comment]
I was thinking this could be in the next release. Shall we just re-tag it @edbennett?

**Comment by edbennett** [comment]
I'm about to PR that will close out the urgent part of this; I'll create a separate issue with a little more detail for the more wide-reaching part
