### ISSUE TITLE
Project application view could position "invite user" under submission message

### ISSUE THREAD

**Issue by markgdawson** [edbennett/cogs3#73]
Personally, I read the message first. Then looked below it for the invite button. It wasn't immediately obvious where it was. Maybe a better/different positioning (e.g. directly under the message) could make this more evident.

http://localhost:8000/en-gb/projects/applications/1/

**Comment by edbennett** [comment]
not sure what you mean here? which submission message? users can't be invited until a project is approved, which happens after the submission message appears…

**Comment by markgdawson** [comment]
We're talking about two different messages I think. I mean the measage box at the top of the project view page.

So create a project, have it approved, then visit the project view page.

**Comment by markgdawson** [comment]
It's my fault. I put "submission message" in the title rather than just "message".

**Comment by markgdawson** [comment]
After discussion with @edbennett, this is a bit clearer now.

The "invite users" button is disabled, and doesn't react to clicking. It shows in blue when enabled, which makes it more prominent. I've highlighted some minor issues with the text in

I'm closing this in favour of minor changes suggested in #97 and #98
