### ISSUE TITLE
Error thrown on when "funding sources" selected from dropdown in funding sources index

### ISSUE THREAD

**Issue by markgdawson** [edbennett/cogs3#86]
Error thrown by endpoint:
http://localhost:8000/en-gb/funding/list/fundingsources/

Seems like the route might be missing

**Comment by markgdawson** [comment]
Same error thrown by:
http://localhost:8000/en-gb/funding/list/publications/

**Comment by edbennett** [comment]
This is a model problem, not a route problem.

`FundingSource` and `Publication` are two subclasses of the `Attribution` model. The views mentioned work by inheriting `AttributionListView` and setting which model to operate on. Within the `get_queryset` method, the queryset is filtered using `fundingsource__in` - i.e. checking the value of the `fundingsource` attribute of the model. This is only defined on the `Attribution` model, not on the `FundingSource` and `Publication` models that inherit from it, hence the error.
