### ISSUE TITLE
Migrations should not be modified

### ISSUE THREAD

**Issue by markgdawson** [edbennett/cogs3#93]
I've noticed some changes to migrations that might have been applied.

This will need to be rolled back, as these migrations will not be applied again.

It might be a good idea to verify with git that all migrations that existed in current live (i.e. 0a17f268ecd3f633bb0643bcde73854639af8d69) have not been changed in current master.

**Comment by edbennett** [comment]
@M4rkD Does M4rkD#3 close this issue or is there more to come?

**Comment by markgdawson** [comment]
I haven't checked the migrations against live yet.

**Comment by markgdawson** [comment]
Checked all migrations, and the ones which existed in the production server are now the same in development.
