### ISSUE TITLE
Invite user button onclick handler to display alert message

### ISSUE THREAD

**Issue by markgdawson** [edbennett/cogs3#98]
The invite button on the project view page do nothing when clicked project is not approved.

As a minimum a standard javascript alert could pop up the same message as is seen in the tooltip with an onclick handler.

**Comment by markgdawson** [comment]
Note: issue opened after closing #73

**Comment by edbennett** [comment]
Alternatively, the button could be hidden. JavaScript alerts are kinda annoying…

The problem with stylised UIs where every website looks different is that a "disabled" button is no longer obviously disabled.

**Comment by markgdawson** [comment]
Very good points. My motivation for this was that hiding the button might also be confusing, since we have a message that instructs users to user the button on this page to add.

But I agree that alerts are ugly and annoying. What about we shove an alert in for now (which is a teeny tiny change) and open an issue to "prettify" it later?

**Comment by markgdawson** [comment]
If we go down that route, maybe this is something that @bjthorpe could quickly roll into the change he's looking at today....?

**Comment by edbennett** [comment]
The alternative would be to remove it and simultaneously change the message to mention that once the project is approved then they will be able to use the Invite button?

**Comment by bjthorpe** [comment]
OK, I have added in a relevant alert message to the button for now. I also took the liberty to do the same for when the max number of users has been reached as that had the same behaviour of doing nothing when it was clicked on. FYI they did display messages telling the user why the button did nothing but only when you hover the mouse over the button which was not very clear.
